swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string

# Transactions

  /user/{accountId}/transactions:
  get:
    tags:
      - User Account Transactions
    summary: Get User Account Transactions
    description: Get transactions of a specific user account with optional filtering by month
    parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - name: accountId
        in: path
        description: User Account ID
        required: true
        type: string
      - name: month
        in: query
        description: Specific month (e.g., '2023-11' for November 2023)
        required: false
        type: string
    consumes:
      - application/json
    produces:
      - application/json
    responses:
      '200':
        description: Successful operation
        schema:
          $ref: '#/definitions/ResponseDetails'
      '400':
        description: Invalid values
      '500':
        description: Internal Server Error
    security:
      - Bearer: []
  post:
    tags:
      - User Account Transactions
    summary: Create a new transaction
    description: Create a new transaction for a specific user account
    parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - name: accountId
        in: path
        description: User Account ID
        required: true
        type: string
    consumes:
      - application/json
    produces:
      - application/json
    requestBody:
      description: Transaction details
      required: true
      content:
        application/json:
          schema:
            $ref: '#/definitions/TransactionInput'
    responses:
      '201':
        description: Transaction created successfully
        schema:
          $ref: '#/definitions/TransactionDetails'
      '400':
        description: Invalid values
      '500':
        description: Internal Server Error
    security:
      - Bearer: []
  /user/{accountId}/transactions/{transactionId}:
  put:
    tags:
      - User Account Transactions
    summary: Update a transaction
    description: Update an existing transaction for a specific user account
    parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      - name: accountId
        in: path
        description: User Account ID
        required: true
        type: string
      - name: transactionId
        in: path
        description: Transaction ID
        required: true
        type: string
    consumes:
      - application/json
    produces:
      - application/json
    requestBody:
      description: Updated Transaction details
      required: true
      content:
        application/json:
          schema:
            $ref: '#/definitions/TransactionInput'
    responses:
      '200':
        description: Transaction updated successfully
        schema:
          $ref: '#/definitions/TransactionDetails'
      '400':
        description: Invalid values
      '404':
        description: Transaction not found
      '500':
        description: Internal Server Error
    security:
      - Bearer: []